[project]
name = "krinon-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
krinon-cli = "krinon_cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
